import { Strategy, Trade } from "@/types/Models"

export const data: Trade[] = [
  {
    id: 1,
    strategy: "Breakout",
    date: "2025-09-05",
    holdingTime: 120,
    pair: "EUR/USD",
    lot: 0.5,
    type: "Long",
    entry: 1.0850,
    entryLogic: "Manual",
    timeFrame: "H1",
    stopLoss: 1.0820,
    exit: 1.0920,
    exitLogic: "TP",
    profitLoss: 70,
    takeProfit: 1.0920,
    notes: "Clean breakout from resistance with volume confirmation.",
    roi: "2%",
    rMultiple: 2.5,
    risk: "FULL",
    rules: "Yes"
  },
  {
    id: 2,
    strategy: "Reversal",
    date: "2025-09-03",
    holdingTime: 45,
    pair: "GBP/USD",
    lot: 0.25,
    type: "Short",
    entry: 1.2735,
    entryLogic: "Limit",
    timeFrame: "M30",
    stopLoss: 1.2760,
    exit: 1.2700,
    exitLogic: "SL",
    profitLoss: -35,
    takeProfit: 1.2650,
    notes: "Price rejected 200 EMA but failed to continue down.",
    roi: "-1%",
    rMultiple: -1.4,
    risk: "HALF",
    rules: "No"
  },
  {
    id: 3,
    strategy: "Trend Following",
    date: "2025-09-01",
    holdingTime: 300,
    pair: "USD/JPY",
    lot: 1.0,
    type: "Long",
    entry: 145.20,
    entryLogic: "Manual",
    timeFrame: "H4",
    stopLoss: 144.80,
    exit: 146.50,
    exitLogic: "TP",
    profitLoss: 130,
    takeProfit: 146.50,
    notes: "Strong uptrend continuation after pullback.",
    roi: "4%",
    rMultiple: 3.25,
    risk: "FULL",
    rules: "Yes"
  }
]

// Dummy array of 3 Strategy objects
export const dummyStrategies: Strategy[] = [
  {
    id: '1',
    name: 'London Breakout',
    description: 'Trade the breakout of the London session range.',
    type: 'Breakout',
    instruments: ['EUR/USD', 'GBP/USD'],
    timeframes: ['M15', 'H1'],
    session: 'London',
    indicators: ['ATR', 'Pivot Points'],
    entryRules: ['Enter on breakout of session high/low'],
    exitRules: ['Exit at 2R or end of session'],
    stopLossRules: ['Below/above session range'],
    takeProfitRules: ['2R from entry'],
    riskManagement: 'Risk 1% per trade',
    tags: ['momentum', 'session']
  },
  {
    id: '2',
    name: 'Moving Average Crossover',
    description: 'Buy when fast MA crosses above slow MA.',
    type: 'Trend',
    instruments: ['USD/JPY'],
    timeframes: ['H1', 'H4'],
    session: 'All',
    indicators: ['EMA50', 'EMA200'],
    entryRules: ['Buy when EMA50 crosses above EMA200'],
    exitRules: ['Exit when EMA50 crosses below EMA200'],
    stopLossRules: ['Below recent swing low'],
    takeProfitRules: ['1.5R from entry'],
    riskManagement: 'Risk 2% per trade',
    tags: ['trend', 'crossover']
  },
  {
    id: '3',
    name: 'RSI Reversal',
    description: 'Fade overbought/oversold RSI readings.',
    type: 'Reversal',
    instruments: ['XAU/USD'],
    timeframes: ['M30'],
    session: 'NewYork',
    indicators: ['RSI'],
    entryRules: ['Sell when RSI > 70', 'Buy when RSI < 30'],
    exitRules: ['Exit at RSI crossing 50'],
    stopLossRules: ['20 pips from entry'],
    takeProfitRules: ['1R from entry'],
    riskManagement: 'Risk 0.5% per trade',
    tags: ['reversal', 'oscillator']
  }
]